MMFMWK-9163 libxa_af_hostless:xf-debug.h: Add macro to avoid double include
There are a build error if compile with DEBUG:
In file included from ..//libxa_af_hostless/algo/host-apf/include/xf.h:52,
                 from ../common/include/library_load.h:28,
                 from src/xaf-fsl-dec-test.c:34:
..//libxa_af_hostless/include/xf-debug.h:105:48:
error: redeclaration of enumerator ‘__xf_trace_0’
  105 | #define TRACE_TAG(tag, on)      enum { __xf_trace_##tag = on }
      |                                                ^~~~~~~~~~~
..//libxa_af_hostless/include/xf-debug.h:135:1:
note: in expansion of macro ‘TRACE_TAG’
  135 | TRACE_TAG(0, 0);
      | ^~~~~~~~~
In file included from ..//testxa_af_hostless/test/include/xaf-utils-test.h:33,
                 from src/xaf-fsl-dec-test.c:29:
..//libxa_af_hostless/include/xf-debug.h:105:48:
note: previous definition of ‘__xf_trace_0’ was here
  105 | #define TRACE_TAG(tag, on)      enum { __xf_trace_##tag = on }
      |                                                ^~~~~~~~~~~
..//libxa_af_hostless/include/xf-debug.h:135:1:
note: in expansion of macro ‘TRACE_TAG’
  135 | TRACE_TAG(0, 0);
      | ^~~~~~~~~

This is caused by double include the header xf-debug.h, add macro to
avoid this.

Signed-off-by: Zhang Peng <peng.zhang_8@nxp.com>